// Generated by make_cards.py from vocab.json. Do not edit by hand.
window.VOCAB_CARDS = [
 {
  "word": "abate",
  "definition": "To lessen in force or intensity; to subside or die down."
 },
 {
  "word": "accede",
  "definition": "To assent or agree, esp. after initial reluctance; to yield."
 },
 {
  "word": "acquiesce",
  "definition": "To accept or comply passively, without protest; to give tacit consent."
 },
 {
  "word": "acrimony",
  "definition": "Bitterness or sharpness of speech or temper, especially in dispute."
 },
 {
  "word": "acumen",
  "definition": "Keenness of judgment; shrewdness in practical matters."
 },
 {
  "word": "adduce",
  "definition": "To cite or offer as evidence or authority in an argument."
 },
 {
  "word": "adjudicate",
  "definition": "To make a formal judgment on a disputed matter."
 },
 {
  "word": "admonish",
  "definition": "To warn or reprove firmly but not harshly; to counsel against."
 },
 {
  "word": "aegis",
  "definition": "The protection, backing, or sponsorship of a person or organization."
 },
 {
  "word": "allay",
  "definition": "To lessen or put to rest (fear, doubt, suspicion)."
 },
 {
  "word": "allude",
  "definition": "To refer to indirectly, without naming the thing outright."
 },
 {
  "word": "ameliorate",
  "definition": "To make better; to improve a bad situation."
 },
 {
  "word": "amenable",
  "definition": "Open to suggestion or persuasion; also, capable of being tested or judged by a given standard."
 },
 {
  "word": "anachronism",
  "definition": "Something placed in the wrong historical period; a chronological misplacement."
 },
 {
  "word": "anomaly",
  "definition": "A deviation from the normal or expected; an irregularity."
 },
 {
  "word": "antipathy",
  "definition": "A settled aversion or dislike; deep-seated opposition."
 },
 {
  "word": "apocryphal",
  "definition": "Of doubtful authenticity, though widely circulated as true."
 },
 {
  "word": "arbiter",
  "definition": "A person with authority to settle a dispute or judge a matter."
 },
 {
  "word": "arcane",
  "definition": "Understood by few; mysterious or obscure."
 },
 {
  "word": "archaic",
  "definition": "Belonging to an earlier period; antiquated or outmoded."
 },
 {
  "word": "ardent",
  "definition": "Intensely enthusiastic or passionate."
 },
 {
  "word": "ascendancy",
  "definition": "A position of dominant power or controlling influence."
 },
 {
  "word": "ascetic",
  "definition": "Practicing severe self-denial, especially for a moral or spiritual end; austere."
 },
 {
  "word": "ascribe",
  "definition": "To attribute or credit (a cause, quality, or authorship) to a source."
 },
 {
  "word": "assiduous",
  "definition": "Showing great care, persistence, and diligence."
 },
 {
  "word": "austere",
  "definition": "Severe or plain; without ornament or comfort."
 },
 {
  "word": "avow",
  "definition": "To assert or declare openly and without shame."
 },
 {
  "word": "belie",
  "definition": "To give a false impression of; to contradict or disguise (not 'to lie about')."
 },
 {
  "word": "benign",
  "definition": "Gentle and harmless; favorable or benevolent."
 },
 {
  "word": "bolster",
  "definition": "To support, strengthen, or reinforce."
 },
 {
  "word": "candor",
  "definition": "Frankness; unreserved honesty of expression."
 },
 {
  "word": "canon",
  "definition": "An authoritative body of works or rules accepted as genuine."
 },
 {
  "word": "capricious",
  "definition": "Given to sudden, unpredictable changes; whimsical."
 },
 {
  "word": "castigate",
  "definition": "To reprimand or criticize severely."
 },
 {
  "word": "censure",
  "definition": "Formal, strong expression of disapproval."
 },
 {
  "word": "charlatan",
  "definition": "One who pretends to expertise he does not have; a quack."
 },
 {
  "word": "circumscribe",
  "definition": "To draw a boundary around; to confine within limits."
 },
 {
  "word": "circumvent",
  "definition": "To get around a rule, obstacle, or difficulty by artful means."
 },
 {
  "word": "coalesce",
  "definition": "To come together to form one whole; to unite."
 },
 {
  "word": "codify",
  "definition": "To arrange (rules or principles) into a systematic code."
 },
 {
  "word": "cogent",
  "definition": "Clear, logical, and convincing."
 },
 {
  "word": "cognizant",
  "definition": "Aware; having knowledge or notice of something."
 },
 {
  "word": "collusion",
  "definition": "Secret cooperation for a deceitful or unlawful purpose."
 },
 {
  "word": "commensurate",
  "definition": "Corresponding in size, degree, or proportion."
 },
 {
  "word": "conciliatory",
  "definition": "Intended to placate or win over an opponent; appeasing."
 },
 {
  "word": "concomitant",
  "definition": "Naturally accompanying or associated."
 },
 {
  "word": "conflate",
  "definition": "To combine two or more distinct things into one, often mistakenly."
 },
 {
  "word": "conjecture",
  "definition": "An opinion or conclusion formed on incomplete evidence; a guess."
 },
 {
  "word": "connoisseur",
  "definition": "An expert judge in matters of taste, especially in the fine arts."
 },
 {
  "word": "connote",
  "definition": "To imply or suggest (an idea or feeling) in addition to the literal meaning."
 },
 {
  "word": "conundrum",
  "definition": "A confusing and difficult problem or riddle."
 },
 {
  "word": "corroborate",
  "definition": "To confirm or support with evidence."
 },
 {
  "word": "countervail",
  "definition": "To counterbalance; to act with equal force against."
 },
 {
  "word": "credulous",
  "definition": "Too ready to believe; easily convinced on slight evidence."
 },
 {
  "word": "culpable",
  "definition": "Deserving blame; at fault."
 },
 {
  "word": "dearth",
  "definition": "A scarcity; an inadequate supply."
 },
 {
  "word": "debase",
  "definition": "To lower in quality, character, or value; to degrade."
 },
 {
  "word": "deference",
  "definition": "Humble submission to the judgment or authority of another."
 },
 {
  "word": "deleterious",
  "definition": "Harmful, especially in a gradual or not-obvious way."
 },
 {
  "word": "delineate",
  "definition": "To describe or portray precisely; to trace the outline of."
 },
 {
  "word": "denigrate",
  "definition": "To disparage; to attack the reputation of."
 },
 {
  "word": "deride",
  "definition": "To express contempt for; to ridicule."
 },
 {
  "word": "dichotomy",
  "definition": "A division into two mutually exclusive or contradictory groups."
 },
 {
  "word": "didactic",
  "definition": "Intended to instruct, esp. morally; sometimes tediously so."
 },
 {
  "word": "diminution",
  "definition": "A reduction in size, extent, or importance."
 },
 {
  "word": "disabuse",
  "definition": "To free someone of a mistaken belief."
 },
 {
  "word": "disinterested",
  "definition": "Impartial; having no stake in the outcome. Not a synonym for uninterested."
 },
 {
  "word": "disparage",
  "definition": "To belittle; to speak of as being of little worth."
 },
 {
  "word": "disparate",
  "definition": "Fundamentally different in kind; not comparable."
 },
 {
  "word": "dispassionate",
  "definition": "Not influenced by emotion; coolly impartial."
 },
 {
  "word": "dissonance",
  "definition": "A tension or clash arising from a lack of agreement or harmony."
 },
 {
  "word": "divulge",
  "definition": "To disclose something previously private or secret."
 },
 {
  "word": "dogmatic",
  "definition": "Asserting opinions as if they were incontrovertibly true."
 },
 {
  "word": "efficacy",
  "definition": "The power to produce a desired result; effectiveness."
 },
 {
  "word": "egalitarian",
  "definition": "Favoring equality of all people."
 },
 {
  "word": "egregious",
  "definition": "Conspicuously bad; flagrant."
 },
 {
  "word": "emulate",
  "definition": "To match or surpass, typically by imitation."
 },
 {
  "word": "endemic",
  "definition": "Native to or characteristically confined to a particular place."
 },
 {
  "word": "engender",
  "definition": "To give rise to; to cause or produce."
 },
 {
  "word": "enmity",
  "definition": "Deep-seated hostility; the state of being enemies."
 },
 {
  "word": "ephemeral",
  "definition": "Lasting a very short time; fleeting."
 },
 {
  "word": "epistemology",
  "definition": "The branch of philosophy concerned with the nature and grounds of knowledge."
 },
 {
  "word": "eschew",
  "definition": "To deliberately avoid or abstain from."
 },
 {
  "word": "esoteric",
  "definition": "Understood by only a small group with specialized knowledge."
 },
 {
  "word": "espouse",
  "definition": "To adopt or support (a cause, belief, or way of life)."
 },
 {
  "word": "evanescent",
  "definition": "Quickly fading or vanishing; fleeting."
 },
 {
  "word": "evince",
  "definition": "To show plainly; to make evident by conduct or expression."
 },
 {
  "word": "exacerbate",
  "definition": "To make (a problem or negative condition) worse."
 },
 {
  "word": "exculpatory",
  "definition": "Tending to clear from blame or accusation."
 },
 {
  "word": "exhort",
  "definition": "To urge strongly by advice or appeal."
 },
 {
  "word": "exigency",
  "definition": "An urgent demand or pressing requirement of a situation."
 },
 {
  "word": "exonerate",
  "definition": "To clear of blame or of a charge."
 },
 {
  "word": "expedient",
  "definition": "Convenient and practical, though possibly improper; self-serving."
 },
 {
  "word": "extant",
  "definition": "Still in existence; surviving."
 },
 {
  "word": "extenuating",
  "definition": "Serving to lessen the seriousness of an offense by partially excusing it."
 },
 {
  "word": "extol",
  "definition": "To praise enthusiastically."
 },
 {
  "word": "extrapolate",
  "definition": "To project known values beyond the observed range; to infer the unobserved from the observed."
 },
 {
  "word": "facile",
  "definition": "Achieved too easily; superficial and lacking depth or rigor."
 },
 {
  "word": "fallacious",
  "definition": "Resting on a logical fallacy; deceptive in its reasoning."
 },
 {
  "word": "fiduciary",
  "definition": "Involving trust, esp. regarding one party's duty to act for another's benefit."
 },
 {
  "word": "foment",
  "definition": "To instigate or stir up (usually something undesirable, like unrest)."
 },
 {
  "word": "forestall",
  "definition": "To prevent or hinder by acting in advance."
 },
 {
  "word": "fortuitous",
  "definition": "Happening by chance. Loosely used to mean lucky; the strict sense is merely accidental."
 },
 {
  "word": "garner",
  "definition": "To gather, collect, or accumulate (esp. support, information, or acclaim)."
 },
 {
  "word": "germane",
  "definition": "Relevant and appropriate to the matter at hand."
 },
 {
  "word": "grandiose",
  "definition": "Impressively or pretentiously grand; inflated in scale or ambition."
 },
 {
  "word": "hegemony",
  "definition": "Leadership or dominance of one group over others."
 },
 {
  "word": "iconoclast",
  "definition": "One who attacks cherished beliefs or established conventions."
 },
 {
  "word": "idiosyncratic",
  "definition": "Peculiar to an individual; distinctively eccentric."
 },
 {
  "word": "illicit",
  "definition": "Not permitted; unlawful or improper. Distinguish from elicit, to draw out."
 },
 {
  "word": "immutable",
  "definition": "Unchanging over time; unable to be altered."
 },
 {
  "word": "impasse",
  "definition": "A position from which there is no way forward; a deadlock."
 },
 {
  "word": "impervious",
  "definition": "Unable to be affected or penetrated (by influence, argument, or substance)."
 },
 {
  "word": "impugn",
  "definition": "To attack as false or questionable; to call into doubt."
 },
 {
  "word": "impute",
  "definition": "To attribute or assign (typically fault, motive, or responsibility) to someone."
 },
 {
  "word": "inadvertent",
  "definition": "Unintentional; resulting from inattention rather than design."
 },
 {
  "word": "incipient",
  "definition": "In an initial stage; beginning to appear."
 },
 {
  "word": "incontestable",
  "definition": "Not open to dispute; beyond challenge."
 },
 {
  "word": "inculcate",
  "definition": "To instill an idea or habit by persistent repetition."
 },
 {
  "word": "indeterminate",
  "definition": "Not fixed or precisely determined; uncertain."
 },
 {
  "word": "inexorable",
  "definition": "Impossible to stop or prevent; relentless."
 },
 {
  "word": "innocuous",
  "definition": "Not harmful or offensive; harmless."
 },
 {
  "word": "intractable",
  "definition": "Hard to control, manage, or solve."
 },
 {
  "word": "jurisprudence",
  "definition": "The theory or philosophy of law."
 },
 {
  "word": "juxtapose",
  "definition": "To place side by side, esp. for contrasting effect."
 },
 {
  "word": "latent",
  "definition": "Existing but not yet developed, manifest, or active."
 },
 {
  "word": "laudable",
  "definition": "Deserving praise; commendable."
 },
 {
  "word": "lexicon",
  "definition": "The vocabulary of a person, language, or field of knowledge."
 },
 {
  "word": "magnanimous",
  "definition": "Generous in forgiving; free of petty resentment."
 },
 {
  "word": "malleable",
  "definition": "Easily shaped, influenced, or adapted; pliable."
 },
 {
  "word": "mendacity",
  "definition": "Untruthfulness; the tendency to lie or deceive."
 },
 {
  "word": "meticulous",
  "definition": "Showing extreme attention to detail; very precise."
 },
 {
  "word": "milieu",
  "definition": "A person's social or cultural environment."
 },
 {
  "word": "mitigate",
  "definition": "To make less severe, serious, or painful; to alleviate."
 },
 {
  "word": "mollify",
  "definition": "To appease or soothe the anger of."
 },
 {
  "word": "myopic",
  "definition": "Lacking foresight or breadth of view; short-sighted."
 },
 {
  "word": "nascent",
  "definition": "Just coming into existence; emerging."
 },
 {
  "word": "notwithstanding",
  "definition": "In spite of; despite. Often placed after the noun it governs."
 },
 {
  "word": "obviate",
  "definition": "To remove (a need or difficulty); to make unnecessary."
 },
 {
  "word": "onerous",
  "definition": "Involving a heavy, burdensome obligation or effort."
 },
 {
  "word": "opprobrium",
  "definition": "Harsh public disgrace or scorn arising from shameful conduct."
 },
 {
  "word": "oscillate",
  "definition": "To swing back and forth between positions or states."
 },
 {
  "word": "ostensible",
  "definition": "Stated or appearing to be true, but not necessarily so."
 },
 {
  "word": "ostracize",
  "definition": "To exclude from a group by common consent."
 },
 {
  "word": "palpable",
  "definition": "So intense as to seem almost tangible; readily perceived."
 },
 {
  "word": "paradigm",
  "definition": "A typical example or model; a framework of assumptions."
 },
 {
  "word": "parochial",
  "definition": "Narrowly limited in scope or outlook; provincial."
 },
 {
  "word": "parsimonious",
  "definition": "Very sparing in use; economical to the point of stinginess."
 },
 {
  "word": "paternalistic",
  "definition": "Limiting a person's freedom on the theory that it is for that person's own good."
 },
 {
  "word": "patronize",
  "definition": "To treat condescendingly; also, to be a customer of. Context decides which sense is meant."
 },
 {
  "word": "paucity",
  "definition": "The presence of something in insufficient quantity; scarcity."
 },
 {
  "word": "pejorative",
  "definition": "Disparaging; conveying disapproval through the choice of word itself."
 },
 {
  "word": "penchant",
  "definition": "A strong and habitual liking or inclination."
 },
 {
  "word": "perfunctory",
  "definition": "Done merely as a routine or duty, with little care or interest."
 },
 {
  "word": "pernicious",
  "definition": "Having a harmful effect, esp. in a gradual or subtle way."
 },
 {
  "word": "piecemeal",
  "definition": "Done a fragment at a time rather than as a whole; unsystematic."
 },
 {
  "word": "pithy",
  "definition": "Brief and full of meaning; terse and pointed."
 },
 {
  "word": "placate",
  "definition": "To soothe or pacify, especially by concession."
 },
 {
  "word": "polemic",
  "definition": "A strong verbal or written attack on an opinion or position."
 },
 {
  "word": "portend",
  "definition": "To be a warning or sign of (a future event); to foreshadow."
 },
 {
  "word": "precarious",
  "definition": "Dangerously insecure or unstable; dependent on uncertain conditions."
 },
 {
  "word": "preclude",
  "definition": "To prevent from happening; to make impossible in advance."
 },
 {
  "word": "preponderance",
  "definition": "A superiority in weight, number, or force; the greater part."
 },
 {
  "word": "prerogative",
  "definition": "An exclusive right or privilege attaching to a position."
 },
 {
  "word": "presupposition",
  "definition": "Something assumed in advance and required for an argument to make sense."
 },
 {
  "word": "prevaricate",
  "definition": "To speak or act evasively so as to avoid the truth."
 },
 {
  "word": "probative",
  "definition": "Serving to prove; affording evidence."
 },
 {
  "word": "prodigious",
  "definition": "Remarkably great in extent, size, or degree."
 },
 {
  "word": "prohibitive",
  "definition": "So high in cost or difficulty as to prevent the thing altogether."
 },
 {
  "word": "proliferate",
  "definition": "To increase or spread rapidly."
 },
 {
  "word": "promulgate",
  "definition": "To promote or make widely known (an idea or doctrine); to put into effect."
 },
 {
  "word": "propensity",
  "definition": "An inclination or natural tendency to behave in a particular way."
 },
 {
  "word": "prosaic",
  "definition": "Commonplace and unimaginative; dull and matter-of-fact."
 },
 {
  "word": "proscribe",
  "definition": "To forbid or condemn officially (not 'prescribe')."
 },
 {
  "word": "purported",
  "definition": "Alleged; claimed to be so without having been established."
 },
 {
  "word": "purview",
  "definition": "The scope of the influence or concerns of something."
 },
 {
  "word": "putative",
  "definition": "Generally considered or reputed to be; supposed."
 },
 {
  "word": "quandary",
  "definition": "A state of perplexity, especially over a choice between unwelcome options."
 },
 {
  "word": "quiescent",
  "definition": "In a state of inactivity or dormancy; quiet."
 },
 {
  "word": "quintessential",
  "definition": "Representing the purest or most perfect example of a kind."
 },
 {
  "word": "quirk",
  "definition": "A peculiarity of behavior; an idiosyncrasy. An unpredictable or unaccountable act or event; a vagary."
 },
 {
  "word": "rebuke",
  "definition": "A sharp expression of disapproval; a reprimand."
 },
 {
  "word": "recalcitrant",
  "definition": "Stubbornly resistant to authority or control."
 },
 {
  "word": "redress",
  "definition": "The setting right of a wrong; remedy or compensation."
 },
 {
  "word": "refute",
  "definition": "To prove (a statement or theory) to be wrong."
 },
 {
  "word": "rejoinder",
  "definition": "A reply, especially a sharp or pointed answer to an objection."
 },
 {
  "word": "relegate",
  "definition": "To consign to an inferior rank or position."
 },
 {
  "word": "repudiate",
  "definition": "To reject or disown; to refuse to accept or be associated with."
 },
 {
  "word": "repugnance",
  "definition": "Strong distaste or aversion; also, inconsistency between two things."
 },
 {
  "word": "salient",
  "definition": "Most noticeable or important; prominent."
 },
 {
  "word": "salutary",
  "definition": "Producing a beneficial effect, esp. a corrective one."
 },
 {
  "word": "sanction",
  "definition": "An imposed penalty for breaking a rule (contronym: it can also mean official approval)."
 },
 {
  "word": "sardonic",
  "definition": "Scornfully mocking; bitterly derisive."
 },
 {
  "word": "scrupulous",
  "definition": "Diligent, thorough, and careful to do what is right."
 },
 {
  "word": "seminal",
  "definition": "Strongly influencing later developments; originative."
 },
 {
  "word": "shrewd",
  "definition": "Having sharp, clever judgment; astute."
 },
 {
  "word": "solipsism",
  "definition": "The theory or self-absorbed view that only the self exists or matters."
 },
 {
  "word": "specious",
  "definition": "Superficially plausible or attractive but actually false or misleading."
 },
 {
  "word": "spurious",
  "definition": "Not genuine; false or illegitimate despite appearances."
 },
 {
  "word": "stipulate",
  "definition": "To specify as a condition of an agreement; to grant a point for the sake of argument."
 },
 {
  "word": "stymie",
  "definition": "To block or thwart; to present an obstacle to."
 },
 {
  "word": "subvert",
  "definition": "To undermine the power or authority of an established system."
 },
 {
  "word": "supercilious",
  "definition": "Haughtily contemptuous; behaving as though superior."
 },
 {
  "word": "supersede",
  "definition": "To take the place of; to displace as obsolete."
 },
 {
  "word": "supplant",
  "definition": "To supersede and replace, esp. by force or scheming."
 },
 {
  "word": "surreptitious",
  "definition": "Done secretly to escape notice; stealthy."
 },
 {
  "word": "tacit",
  "definition": "Understood or implied without being stated."
 },
 {
  "word": "tangential",
  "definition": "Only slightly relevant; diverging from the main point."
 },
 {
  "word": "tantamount",
  "definition": "Equivalent in effect or value to something else."
 },
 {
  "word": "tautology",
  "definition": "A statement true by its own terms and so empty of content; needless repetition."
 },
 {
  "word": "tenable",
  "definition": "Able to be defended against attack or objection."
 },
 {
  "word": "tenacious",
  "definition": "Holding firmly; persistent and not easily dislodged."
 },
 {
  "word": "tenuous",
  "definition": "Very weak or slight; lacking a firm basis."
 },
 {
  "word": "ubiquitous",
  "definition": "Present or found everywhere."
 },
 {
  "word": "unconscionable",
  "definition": "Not guided by conscience; unreasonably excessive or shockingly unfair."
 },
 {
  "word": "unequivocal",
  "definition": "Admitting of no doubt or misinterpretation; unambiguous."
 },
 {
  "word": "unscrupulous",
  "definition": "Without moral principle; unrestrained by conscience."
 },
 {
  "word": "untenable",
  "definition": "Not able to be defended against attack or objection."
 },
 {
  "word": "unwarranted",
  "definition": "Not justified by the evidence or the circumstances."
 },
 {
  "word": "vacillate",
  "definition": "To waver indecisively between different opinions or actions."
 },
 {
  "word": "venerate",
  "definition": "To regard with deep respect or reverence."
 },
 {
  "word": "veracity",
  "definition": "Conformity to truth; accuracy or truthfulness."
 },
 {
  "word": "vernacular",
  "definition": "The everyday language or dialect of ordinary people."
 },
 {
  "word": "vestige",
  "definition": "A trace or remnant of something that is no longer present."
 },
 {
  "word": "vicarious",
  "definition": "Experienced indirectly, through another rather than firsthand."
 },
 {
  "word": "vindicate",
  "definition": "To clear of blame; to show to be justified or correct."
 },
 {
  "word": "virulent",
  "definition": "Extremely severe, harmful, or hostile."
 },
 {
  "word": "volitional",
  "definition": "Of or resulting from an exercise of the will; chosen rather than compelled."
 },
 {
  "word": "voracious",
  "definition": "Wanting or consuming great quantities; insatiably eager."
 },
 {
  "word": "zenith",
  "definition": "The highest point or culmination."
 }
];
